
name: CI
on: [push, pull_request]
jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install uv
      uses: astral-sh/setup-uv@v7
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    - name: Run tests
      env:
          QVAPAY_APP_ID: ${{ secrets.QVAPAY_APP_ID }}
          QVAPAY_APP_SECRET: ${{ secrets.QVAPAY_APP_SECRET }}
      run: make tests
    - name: Upload coverage
      uses: codecov/codecov-action@v5
      # with:
      #   token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
